HBSD: Use unbound-host with hbsd-update.
Signed-off-by:	Shawn Webb <shawn.webb@hardenedbsd.org>
Hat-tip-to:	@Habbie
MFC-to:		11-STABLE
MFC-to:		10-STABLE
X-MFC-with:	95419a39b106443240775f990592a190522d54cb

diff --git a/usr.sbin/hbsd-update/hbsd-update b/usr.sbin/hbsd-update/hbsd-update
--- a/usr.sbin/hbsd-update/hbsd-update
+++ b/usr.sbin/hbsd-update/hbsd-update
@@ -67,6 +67,7 @@ TAR="/usr/bin/tar"
 SHA256="/sbin/sha256"
 SHA512="/sbin/sha512"
 TAIL="/usr/bin/tail"
+UNBOUND_HOST="/usr/sbin/unbound-host"
 
 debug_print() {
 	echo -e "${1}" >&2
@@ -129,19 +130,30 @@ dnssec_check() {
 	case "${dnssec}" in
 		[yY]*)
 			debug_print "[*] Looking up version info with DNSSEC enabled."
-			val=$(${DRILL} -TD  \
-				-k ${mountpoint}/${dnssec_key} \
-				${dnsrec} txt 2>&1 | \
-				${GREP} '^\[T\]' | \
-				${TAIL} -n 1)
-			rec=$(echo ${val} | awk '{print $2;}')
+			val=$(${UNBOUND_HOST} \
+				-v \
+				-t txt \
+				-f ${mountpoint}/${dnssec_key} \
+				${dnsrec})
 
-			# drill will append an extra period at the end
-			if [ ! "${rec}" = "${dnsrec}." ]; then
+			if ! echo ${val} | grep -qF 'has TXT record'; then
+				debug_print "[-] Could not get DNS record: ${val}"
 				return 1
 			fi
 
-			echo ${val} | awk '{print $6;}' | sed 's,",,g'
+			if echo ${val} | grep -qF 'failed'; then
+				debug_print "[-] DNSSEC validation failed."
+				return 2
+			fi
+
+			t=$(echo ${val} | awk '{print $6;}')
+			if [ ! "$(echo ${val} | awk '{print $6;}')" = "(secure)" ]; then
+				debug_print "[*] DNSSEC validation failed: ${t}."
+				return 2
+			fi
+
+			echo ${val} | awk '{print $5;}' | sed 's,",,g'
+
 			;;
 		*)
 			${DRILL} ${dnsrec} txt | \
@@ -169,6 +181,11 @@ get_version() {
 
 	# Prefer DNS, fallback to HTTP
 	res=$(dnssec_check)
+	if [ ${?} -eq 2 ]; then
+		debug_print "    [-] Bailing."
+		return 1
+	fi
+
 	buildver=$(echo ${res} | ${SED} 's,|, ,g' | ${AWK} '{print $2;}')
 	update_hash=$(echo ${res} | ${SED} 's,|, ,g' | ${AWK} '{print $3;}')
 
