HBSD: Really bring hbsd-update current
The previous commit to bring hbsd-update current got mangled somehow.
I've now fixed the mangling and verified the fix.

Signed-off-by:	Shawn Webb <shawn.webb@hardenedbsd.org>
Sponsored-by:	SoldierX

diff --git a/usr.sbin/hbsd-update/hbsd-update b/usr.sbin/hbsd-update/hbsd-update
--- a/usr.sbin/hbsd-update/hbsd-update
+++ b/usr.sbin/hbsd-update/hbsd-update
@@ -40,6 +40,7 @@ kernel=""
 # hbsd-update.conf(5).
 dnssec="yes"
 dnssec_key="/usr/share/keys/hbsd-update/trusted/dnssec.key"
+revoke_dir="/usr/share/keys/hbsd-update/revoked"
 
 ignorever=0
 unsigned=0
@@ -50,28 +51,33 @@ no_obsolete=0
 interactive=0
 install_src=0
 keeptmp=0
-local_resolver=1
+local_resolver=0
+nodownload=0
+fetchonly=0
+nobase=0
 
 update_hash=""
 
 AWK="/usr/bin/awk"
 BEADM="/usr/local/sbin/beadm"
+CAT="/bin/cat"
 CHFLAGS="/bin/chflags"
 DRILL="/usr/bin/drill"
 ETCUPDATE="/usr/sbin/etcupdate"
 FETCH="/usr/bin/fetch"
+FIND="/usr/bin/find"
 GREP="/usr/bin/grep"
 JLS="/usr/sbin/jls"
 KLDXREF="/usr/sbin/kldxref"
 MKTEMP="/usr/bin/mktemp"
 OPENSSL="/usr/bin/openssl"
+PWD_MKDB="/usr/sbin/pwd_mkdb"
 SED="/usr/bin/sed"
-TAR="/usr/bin/tar"
 SHA256="/sbin/sha256"
 SHA512="/sbin/sha512"
 TAIL="/usr/bin/tail"
+TAR="/usr/bin/tar"
 UNBOUND_HOST="/usr/sbin/unbound-host"
-PWD_MKDB="/usr/sbin/pwd_mkdb"
 
 debug_print() {
 	echo -e "${1}" >&2
@@ -83,6 +89,7 @@ usage() {
 	debug_print "\t-b BEname\tInstall updates to ZFS Boot Environment <BEname>"
 	debug_print "\t-c config\tUse a non-default config file"
 	debug_print "\t-d\t\tDo not use DNSSEC validation"
+	debug_print "\t-f\t\tFetch only"
 	debug_print "\t-h\t\tShow this help screen"
 	debug_print "\t-I\t\tInteractively remove obsolete files"
 	debug_print "\t-i\t\tIgnore version check"
@@ -91,6 +98,7 @@ usage() {
 	debug_print "\t-k kernel\tUse kernel <kernel>"
 	debug_print "\t-n\t\tDo not install kernel"
 	debug_print "\t-o\t\tDo not remove obsolete files/directories"
+	debug_print "\t-r path\tBootstrap root directory <path>"
 	debug_print "\t-s\t\tInstall sources (if present)"
 	debug_print "\t-t tmpdir\tTemporary directory"
 	debug_print "\t-U\t\tAllow unsigned updates"
@@ -149,11 +157,11 @@ get_last_field() {
 }
 
 dnssec_check() {
+	local resolver_flag
+	local is_secure
+	local rec
 	local res
 	local val
-	local rec
-	local is_secure
-	local resolver_flag
 
 	if [ ${local_resolver} -gt 0 ]; then
 		resolver_flag="-r"
@@ -161,14 +169,17 @@ dnssec_check() {
 
 	case "${dnssec}" in
 		[yY]*)
-			debug_print "[*] Looking up version info with DNSSEC enabled."
-			val=$(${UNBOUND_HOST} \
+			if [ ${verbose} -gt 0 ]; then
+				debug_print "[*] Looking up version info with DNSSEC enabled."
+			fi
+			${UNBOUND_HOST} \
 				${resolver_flag} \
 				-v \
 				-t txt \
 				-f ${mountpoint}/${dnssec_key} \
-				${dnsrec} | ${TAIL} -n 1)
+				${dnsrec} > ${tmpdir}/resolver.txt
 
+			val=$(${TAIL} -n 1 ${tmpdir}/resolver.txt)
 			if ! echo ${val} | grep -qF 'has TXT record'; then
 				debug_print "[-] Could not get DNS record."
 				return 2
@@ -362,9 +373,23 @@ fetch_update() {
 }
 
 check_pubkey_validity() {
+	local updatehash
+	local filehash
+	local f
+
 	if [ ${verbose} -gt 0 ]; then
 		debug_print "[*] Checking validity of the public key"
 	fi
+
+	updatehash=$(${SHA256} -q ${tmpdir}/pubkey.pem)
+
+	for f in $(${FIND} ${mountpoint}/usr/share/keys/hbsd-update/revoked -type f); do
+		filehash=$(${SHA256} -q ${f})
+		if [ "${filehash}" = "${updatehash}" ]; then
+			echo "[-] This update has been signed with a revoked key." >&2
+			return 1
+		fi
+	done
 
 	caopt="-CApath"
 	if [ -f ${capath} ]; then
@@ -379,6 +404,50 @@ check_pubkey_validity() {
 	return ${res}
 }
 
+validate_file() {
+	local res
+	local expected_hash
+	local computed_hash
+	local file
+	local defaulterror
+
+	file="${1}"
+	defaulterror=1
+	if [ ! -z "${2}" ]; then
+		defaulterror=${2}
+	fi
+
+	if [ -z "${file}" ]; then
+		debug_print "[-] validate_file: No file specified."
+		return 1
+	fi
+
+	if [ ! -f ${tmpdir}/${file} ]; then
+		return ${defaulterror}
+	fi
+
+	if [ ! -f ${tmpdir}/${file}.sig ]; then
+		return 1
+	fi
+
+	expected_hash=$(${OPENSSL} rsautl \
+	    -verify \
+	    -in ${tmpdir}/${file}.sig \
+	    -pubin \
+	    -inkey ${tmpdir}/pubkey.rsa.pem)
+	res=${?}
+	if [ ${res} -gt 0 ]; then
+		return 1
+	fi
+
+	computed_hash=$(${SHA512} -q ${tmpdir}/${file})
+	if [ ! "${expected_hash}" = "${computed_hash}" ]; then
+		return 1
+	fi
+
+	return 0
+}
+
 check_set_validity() {
 	local res
 	local checkfiles
@@ -386,7 +455,7 @@ check_set_validity() {
 	local signedhash
 	local computedhash
 
-	checkfiles="base.txz etcupdate.tbz skip.txt"
+	checkfiles="base.txz etcupdate.tbz skip.txt mtree.tar"
 	extrafiles="ObsoleteFiles.txt ObsoleteDirs.txt script.sh"
 
 	if [ ${no_kernel} -eq 0 ]; then
@@ -421,50 +490,21 @@ check_set_validity() {
 			debug_print "[*] Checking the validity of ${file}"
 		fi
 
-		signedhash=$(${OPENSSL} rsautl \
-			-verify \
-			-in ${tmpdir}/${file}.sig \
-			-pubin \
-			-inkey ${tmpdir}/pubkey.rsa.pem)
-
-		computedhash=$(${SHA512} -q ${tmpdir}/${file})
-		res=${?}
-		if [ ${res} -gt 0 ]; then
-			return 1
-		fi
-
-		if [ ! "${signedhash}" = "${computedhash}" ]; then
-			debug_print "[-] Hashes don't match for ${file}. Signed: ${signedhash}. Computed ${computedhash}."
+		if ! validate_file ${file}; then
+			debug_print "[-] ${file} failed to validate"
 			return 1
 		fi
 	done
 
+	# Extra files are optional files that we only care about if
+	# they exist. They must be signed if they exist.
 	for file in ${extrafiles}; do
-		if [ ! -f ${tmpdir}/${file} ]; then
-			if [ "$file"} != "script.sh" ]; then
-				debug_print "[-] Warning: Could not find extra file ${file}.  Skipping validity checks for that file."
-			fi
-			continue
-		fi
-
 		if [ ${verbose} -gt 0 ]; then
 			debug_print "[*] Checking the validity of ${file}"
 		fi
 
-		signedhash=$(${OPENSSL} rsautl \
-			-verify \
-			-in ${tmpdir}/${file}.sig \
-			-pubin \
-			-inkey ${tmpdir}/pubkey.rsa.pem)
-
-		computedhash=$(${SHA512} -q ${tmpdir}/${file})
-		res=${?}
-		if [ ${res} -gt 0 ]; then
-			return 1
-		fi
-
-		if [ ! "${signedhash}" = "${computedhash}" ]; then
-			debug_print "[-] Hashes don't match for ${file}. Signed: ${signedhash}. Computed ${computedhash}."
+		if ! validate_file ${file} 0; then
+			debug_print "[-] ${file} failed to validate"
 			return 1
 		fi
 	done
@@ -472,26 +512,97 @@ check_set_validity() {
 	return 0
 }
 
+apply_mtree() {
+	local res
+
+	if [ ${verbose} -gt 0 ]; then
+		debug_print "[*] Applying the mtree"
+	fi
+
+	if [ ! -f ${tmpdir}/mtree.tar ]; then
+		return 0
+	fi
+
+	mkdir ${tmpdir}/mtree
+	if [ ${?} -gt 0 ]; then
+		return 1
+	fi
+
+	tar -xf ${tmpdir}/mtree.tar -C ${tmpdir}/mtree
+	res=${?}
+	if [ ${res} -gt 0 ]; then
+		return 1
+	fi
+
+	mtree -eU \
+	    -f ${tmpdir}/mtree/BSD.root.dist \
+	    -p ${mountpoint}
+	res=${?}
+	if [ ${res} -gt 0 ]; then
+		return 1
+	fi
+
+	mtree -eU \
+	    -f ${tmpdir}/mtree/BSD.usr.dist \
+	    -p ${mountpoint}/usr
+	res=${?}
+	if [ ${res} -gt 0 ]; then
+		return 1
+	fi
+
+	mtree -eU \
+	    -f ${tmpdir}/mtree/BSD.include.dist \
+	    -p ${mountpoint}/usr/include
+	res=${?}
+	if [ ${res} -gt 0 ]; then
+		return 1
+	fi
+
+	mtree -eU \
+	    -f ${tmpdir}/mtree/BSD.var.dist \
+	    -p ${mountpoint}/var
+	res=${?}
+	if [ ${res} -gt 0 ]; then
+		return 1
+	fi
+
+	if [ -f ${tmpdir}/mtree/BSD.tests.dist ]; then
+		mkdir -p ${mountpoint}/usr/tests
+		mtree -eU \
+		    -f ${tmpdir}/mtree/BSD.tests.dist \
+		    -p ${mountpoint}/usr/tests
+	fi
+	res=${?}
+	if [ ${res} -gt 0 ]; then
+		return 1
+	fi
+
+	return 0
+}
+
 apply_base() {
 	local needsresolve
+	local dirs
+	local dir
+	local res
+	local d
+
 	needsresolve=0
+	dirs="/bin /sbin /lib /libexec /usr/bin /usr/sbin /usr/lib"
 
 	if [ ${verbose} -gt 0 ]; then
 		debug_print "[*] Applying base"
 	fi
 
-	${CHFLAGS} -R noschg \
-		${mountpoint}/bin \
-		${mountpoint}/sbin \
-		${mountpoint}/lib \
-		${mountpoint}/libexec \
-		${mountpoint}/usr/bin \
-		${mountpoint}/usr/sbin \
-		${mountpoint}/usr/lib
-	res=${?}
-	if [ ${res} -gt 0 ]; then
-		return ${res}
-	fi
+	for dir in ${dirs}; do
+		if [ -d ${mountpoint}/${dir} ]; then
+			${CHFLAGS} -R noschg ${mountpoint}/${dir}
+			res=${?}
+			if [ ${res} -gt 0 ]; then
+				return ${res}
+			fi
+		fi
+	done
 
 	${TAR} -xpf ${tmpdir}/base.txz \
 		-X ${tmpdir}/skip.txt \
@@ -503,6 +614,7 @@ apply_base() {
 	fi
 
 	boottmp=$(env TMPDIR=${tmpdir} ${MKTEMP} -d)
+	[ ! -d ${mountpoint}/boot ] && mkdir ${mountpoint}/boot
 	${TAR} -xpf ${tmpdir}/base.txz --include ./boot -C ${boottmp}
 	${TAR} -c -C ${boottmp}/boot -f - . | \
 		(cd ${mountpoint}/boot; ${TAR} -xpf -)
@@ -518,6 +630,27 @@ apply_base() {
 			if [ ${verbose} -gt 0 ]; then
 				debug_print "[*] Installing sources"
 			fi
+
+			${FIND} ${mountpoint}/usr/src -type f -delete
+			res=${?}
+			if [ ${res} -gt 0 ]; then
+				echo "[-] Removing source files failed." >&2
+				return 1
+			fi
+
+			for d in $(${FIND} ${mountpoint}/usr/src -type d -depth 1); do
+				# Skip the .zfs directory
+				if [ ${d} = "${mountpoint}/usr/src/.zfs" ]; then
+					continue
+				fi
+
+				rm -rf ${d}
+				res=${?}
+				if [ ${res} -gt 0 ]; then
+					echo "[-] Removing source directories failed" >&2
+					return 1
+				fi
+			done
 
 			${TAR} -xpf ${tmpdir}/src.txz \
 				-C ${mountpoint}
@@ -839,6 +972,11 @@ check_sanity() {
 		exit 1
 	fi
 
+	if [ ${fetchonly} -gt 0 ] && [ ${nodownload} -gt 0 ]; then
+		debug_print "[-] Fetch only and no download options are mutually exclusive"
+		exit 1
+	fi
+
 	if [ ! -z "${zfsbe}" ] && [ ! -x ${BEADM} ]; then
 		debug_print "[-] Please install sysutils/beadm"
 		exit 1
@@ -846,9 +984,11 @@ check_sanity() {
 }
 
 report_version() {
+	get_tmpdir > /dev/null
 	get_version > /dev/null 2>&1
 	if [ ! ${?} -eq 0 ]; then
 		echo "[-] Could not get remote version number" >&2
+		cleanup
 		exit 1
 	fi
 
@@ -864,6 +1004,7 @@ report_version() {
 
 	echo
 
+	cleanup
 	exit 0
 }
 
@@ -883,10 +1024,13 @@ main() {
 	local_kernel=""
 	no_kernel=0
 
-	while getopts 'dhinosCITUVb:c:j:K:k:t:u:v:' opt; do
+	while getopts 'dfhinosBCDITUVb:c:j:K:k:r:t:u:v:' opt; do
 		case "${opt}" in
 			b)
 				zfsbe="${OPTARG}"
+				;;
+			B)
+				nobase=1
 				;;
 			c)
 				configfile="${OPTARG}"
@@ -896,6 +1040,12 @@ main() {
 				;;
 			d)
 				dnssec="no"
+				;;
+			D)
+				nodownload=1
+				;;
+			f)
+				fetchonly=1
 				;;
 			i)
 				ignorever=1
@@ -917,6 +1067,9 @@ main() {
 				;;
 			o)
 				no_obsolete=1
+				;;
+			r)
+				mountpoint="${OPTARG}"
 				;;
 			s)
 				install_src=1
@@ -957,16 +1110,26 @@ main() {
 		kernel=${local_kernel}
 	fi
 
+	if [ ! -d ${mountpoint} ]; then
+		debug_print "[-] ${mountpoint} does not exist"
+		cleanup
+		exit 1
+	fi
+
 	trap sigint_handler INT
 
 	if [ -z "${tmpdir}" ]; then
 		get_tmpdir > /dev/null
 	fi
 
-	get_version > /dev/null 2>&1
+	get_version
 	res=${?}
 	if [ ${res} -gt 0 ]; then
 		debug_print "[*] Could not get the version number"
+		if [ -f ${tmpdir}/resolver.txt ]; then
+			debug_print "[*] Raw DNS result:"
+			${CAT} ${tmpdir}/resolver.txt
+		fi
 		cleanup
 		exit 1
 	fi
@@ -979,11 +1142,17 @@ main() {
 		exit 0
 	fi
 
-	fetch_update
-	res=${?}
-	if [ ${res} -gt 0 ]; then
-		cleanup
-		exit 1
+	if [ ${nodownload} -eq 0 ]; then
+		fetch_update
+		res=${?}
+		if [ ${res} -gt 0 ]; then
+			cleanup
+			exit 1
+		fi
+	fi
+
+	if [ ${fetchonly} -gt 0 ]; then
+		exit 0
 	fi
 
 	set_kernel_config
@@ -1032,12 +1201,22 @@ main() {
 
 	trap 'sigint_handler 1' INT
 
-	apply_base
-	res=${?}
-	if [ ${res} -gt 0 ]; then
-		cleanup
-		destroy_be
-		exit 1
+	if [ ${nobase} -eq 0 ]; then
+		apply_mtree
+		res=${?}
+		if [ ${res} -gt 0 ]; then
+			cleanup
+			destroy_be
+			exit 1
+		fi
+
+		apply_base
+		res=${?}
+		if [ ${res} -gt 0 ]; then
+			cleanup
+			destroy_be
+			exit 1
+		fi
 	fi
 
 	if [ ${no_kernel} -eq 0 ]; then
