HBSD: Intelligently discover the kernel config in hbsd-update.
Signed-off-by:	Shawn Webb <shawn.webb@hardenedbsd.org>
Reported-by:	Johannes Meixner (@xmj)
github-issue:	#196
MFC-to:		10-STABLE

diff --git a/usr.sbin/hbsd-update/hbsd-update b/usr.sbin/hbsd-update/hbsd-update
--- a/usr.sbin/hbsd-update/hbsd-update
+++ b/usr.sbin/hbsd-update/hbsd-update
@@ -34,6 +34,7 @@ zfsbe=""
 backupkern="kernel.old"
 configfile="/etc/hbsd-update.conf"
 mountpoint="/"
+kernel=""
 
 ignorever=0
 unsigned=0
@@ -65,6 +66,7 @@ usage() {
 	debug_print "\t-h\t\tShow this help screen"
 	debug_print "\t-j jailname\tInstall updates to jail <jailname>"
 	debug_print "\t-K backupkern\tBackup the previous kernel to <backupkern>"
+	debug_print "\t-k kernel\tUse kernel <kernel>"
 	debug_print "\t-t tmpdir\tTemporary directory"
 	debug_print "\t-U\t\tAllow unsigned updates"
 	debug_print "\t-v version\tUse a different version"
@@ -299,6 +301,37 @@ apply_base() {
 	return 0
 }
 
+set_kernel_config() {
+	local cur_kernel
+
+	if [ ! -z "${kernel}" ]; then
+		if [ ! -f "${tmpdir}/kernel-${kernel}.txz" ]; then
+			echo "[-] Could not find any applicable kernels" >&2
+			return 1
+		fi
+
+		return 0
+	fi
+
+	cur_kernel=$(uname -v)
+	cur_kernel=${cur_kernel##*/}
+	cur_kernel=$(echo "${cur_kernel}" | sed 's/ //g')
+
+	f="${tmpdir}/kernel-${cur_kernel}.txz"
+	if [ -f "${f}" ]; then
+		kernel=${cur_kernel}
+	else
+		kernel="HARDENEDBSD"
+	fi
+
+	if [ ! -f "${tmpdir}/kernel-${kernel}.txz" ]; then
+		echo "[-] Could not find any applicable kernels" >&2
+		return 1
+	fi
+
+	return 0
+}
+
 apply_kernel() {
 	if [ ${verbose} -gt 0 ]; then
 		debug_print "[*] Applying kernel ${kernel}"
@@ -440,11 +473,6 @@ check_sanity() {
 		exit 1
 	fi
 
-	if [ -z "${kernel}" ]; then
-		debug_print "[-] Missing setting: kernel"
-		exit 1
-	fi
-
 	if [ ! -z "${zfsbe}" ] && [ ! -z "${jailname}" ]; then
 		debug_print "[-] ZFS BE and Jail options are mutually exclusive"
 		exit 1
@@ -470,10 +498,12 @@ report_version() {
 
 main() {
 	local do_report_version
+	local local_kernel
 
 	do_report_version=0
+	local_kernel=""
 
-	while getopts 'hiCUVb:c:j:K:t:u:v:' opt; do
+	while getopts 'hiCUVb:c:j:K:k:t:u:v:' opt; do
 		case "${opt}" in
 			b)
 				if ! which -s ${BEADM}; then
@@ -497,6 +527,9 @@ main() {
 				;;
 			K)
 				backupkern="${OPTARG}"
+				;;
+			k)
+				local_kernel="${OPTARG}"
 				;;
 			t)
 				tmpdir="${OPTARG}"
@@ -527,6 +560,10 @@ main() {
 		report_version
 	fi
 
+	if [ ! -z "${local_kernel}" ]; then
+		kernel=${local_kernel}
+	fi
+
 	if [ -z "${tmpdir}" ]; then
 		get_tmpdir > /dev/null
 	fi
@@ -550,6 +587,13 @@ main() {
 	fi
 
 	fetch_update
+	res=${?}
+	if [ ${res} -gt 0 ]; then
+		cleanup
+		exit 1
+	fi
+
+	set_kernel_config
 	res=${?}
 	if [ ${res} -gt 0 ]; then
 		cleanup
